FROM rustlang/rust:nightly-slim
WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm src/main.rs

COPY src ./src

EXPOSE 3000

CMD ["cargo", "watch", "-x", "run"]