FROM rustlang/rust:nightly-slim AS builder
WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release

COPY src ./src

CMD ["cargo", "watch", "-x", "run"]